#!/usr/bin/env bash
# Copyright 2019-2024 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

##############################################################################################################
# Extract key results from the reports generated by ...
#   "INSIDER Static Application Security Testing" (SAST) - https://github.com/insidersec/insider & https://insidersec.io/
##############################################################################################################

# ----- Please adjust

# ------ Do not modify
VERSION=${INSIDER_VERSION}
STEP=$(get_step)
SEPARATOR=","
APP_BASE=${REPORTS_DIR}/${STEP}__INSIDER
# FIXDIR
APP_DIR_OUT="${APP_BASE}__${APP_GROUP}"
RESULT_FILE="${APP_DIR_OUT}/${APP_GROUP}___results_extracted.csv"
export LOG_FILE="${APP_BASE}.log"

function generate_csv() {
	echo "Applications${SEPARATOR}Insider SAST vulns" >"${RESULT_FILE}"
	while read -r FILE; do
		APP="$(basename "${FILE}")"
		log_extract_message "app '${APP}'"
		JSON_IN="${APP_DIR_OUT}/${APP}_report.json"
		VULNS="n/a"
		if [ -f "${JSON_IN}" ]; then
			VULNS="0"
			COUNT_VULNS=$(jq ".total" "${JSON_IN}")
			[ -n "${COUNT_VULNS}" ] && VULNS=${COUNT_VULNS}
		fi
		echo "${APP}${SEPARATOR}${VULNS}" >>"${RESULT_FILE}"
	done <"${REPORTS_DIR}/list__${APP_GROUP}__all_apps.txt"
	log_console_success "Results: ${RESULT_FILE}"
}

function main() {
	if [[ -d "${APP_DIR_OUT}" ]]; then
		generate_csv
	else
		LOG_FILE=/dev/null
		log_console_error "INSIDER result directory does not exist: ${APP_DIR_OUT}"
	fi
}

main
