#!/usr/bin/env bash
# Copyright 2019-2024 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

##############################################################################################################
# Extract key results from the reports generated by ...
#   "OSV" - https://osv.dev/
##############################################################################################################

# ----- Please adjust

# ------ Do not modify
VERSION=${OSV_VERSION}
STEP=$(get_step)
SEPARATOR=","

APP_DIR_OUT="${REPORTS_DIR}/${STEP}__OSV"
RESULT_FILE="${REPORTS_DIR}/${STEP}__OSV/_results__security__osv.csv"
LOG_FILE="${REPORTS_DIR}/${STEP}__OSV.log"

function generate_csv() {
	echo "Applications${SEPARATOR}OSV vulns" >"${RESULT_FILE}"
	while read -r APP; do
		APP_NAME="$(basename "${APP}")"
		log_extract_message "app '${APP_NAME}'"
		OSV_OUTPUT="${APP_DIR_OUT}/${APP_NAME}_osv.json"
		COUNT_VULNS="n/a"
		if [ -f "${OSV_OUTPUT}" ]; then
			COUNT_VULNS=$(jq -r '[ .results[].packages[] .vulnerabilities[] ] | length' "${OSV_OUTPUT}")
		fi
		echo "${APP_NAME}${SEPARATOR}${COUNT_VULNS}" >>"${RESULT_FILE}"
	done <"${REPORTS_DIR}/00__Weave/list__all_apps.txt"
	log_console_success "Results: ${RESULT_FILE}"
}

function main() {
	if [[ -d "${APP_DIR_OUT}" ]]; then
		generate_csv
	else
		LOG_FILE=/dev/null
		log_console_error "OSV result directory does not exist: ${APP_DIR_OUT}"
	fi
}

main
